package main

// login_test.go — hermetic integration tests for spawnctl login/logout/refresh.
//
// Test harness: real authsvc.Service.Handler() + githubfake over httptest.
// Pattern mirrors internal/authsvc/http_test.go (TestHandlerFullVertical).
// No real network, no real GitHub, no real browser.

import (
	"bufio"
	"context"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"spawnery/internal/authsvc"
	"spawnery/internal/authsvc/githubfake"
	"spawnery/internal/authsvc/store"
	"spawnery/internal/pki"
)

// lazyTestMux allows wiring the AS handler after the server URL is known.
type lazyTestMux struct {
	real http.Handler
}

func (l *lazyTestMux) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if l.real == nil {
		http.Error(w, "not ready", http.StatusServiceUnavailable)
		return
	}
	l.real.ServeHTTP(w, r)
}

// buildTestAS creates a real authsvc Service + httptest.Server with a loopback anchor registered.
// nowFn is the clock the AS uses; pass nil to use real time (required for /refresh PoP tests).
func buildTestAS(t *testing.T, fake *githubfake.Fake, nowFn func() time.Time) (*httptest.Server, store.Store, authsvc.IdPConfig) {
	t.Helper()

	_, sigKey, _ := ed25519.GenerateKey(rand.Reader)
	st := store.NewTestStore(t)

	root, err := pki.NewRootCA("Test Root")
	if err != nil {
		t.Fatal(err)
	}
	inter, err := root.NewIntermediate(pki.ClassSelfHosted)
	if err != nil {
		t.Fatal(err)
	}

	lm := &lazyTestMux{}
	srv := httptest.NewServer(lm)
	t.Cleanup(srv.Close)

	if nowFn == nil {
		nowFn = time.Now
	}
	cfg := authsvc.IdPConfig{
		Store:               st,
		GitHub:              authsvc.NewGitHubProvider(fake.URL(), fake.URL(), fake.ClientID, fake.ClientSecret),
		SigningKey:           sigKey,
		GitHubRedirectURI:   srv.URL + "/oauth/callback",
		SPAOrigin:           "http://localhost:3000",
		RedirectURIs:        []string{"http://localhost:3000/callback", "http://127.0.0.1:8000/cb"},
		VerificationURI:     srv.URL + "/device/verify",
		RegistrationEnabled: true,
		Now:                 nowFn,
	}
	idp, err := authsvc.NewIdP(cfg)
	if err != nil {
		t.Fatal(err)
	}
	svc := authsvc.New(root.Cert, inter, authsvc.WithIdP(idp))
	lm.real = svc.Handler()

	return srv, st, cfg
}

// noRedirClient returns an http.Client that does not follow redirects.
func noRedirClient() *http.Client {
	return &http.Client{
		CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

// driveLoopbackFlow acts as the "browser": authorize → githubfake → AS callback → spawnctl /cb.
// sessKeyB64 is the session pubkey embedded in the authorize URL; cbURL is the spawnctl listener.
// csrfState must match the state generated by loginLoopback (extracted from the authorize URL it prints).
func driveLoopbackFlow(t *testing.T, asSrv *httptest.Server, fake *githubfake.Fake, cbURL, sessKeyB64, csrfState string) {
	t.Helper()
	cl := noRedirClient()

	authURL := asSrv.URL + "/oauth/authorize?" + url.Values{
		"redirect_uri":          {cbURL},
		"state":                 {csrfState},
		"session_pubkey":        {sessKeyB64},
		"code_challenge":        {"E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"},
		"code_challenge_method": {"S256"},
	}.Encode()

	authResp, err := cl.Get(authURL)
	if err != nil {
		t.Fatalf("driveLoopback/authorize: %v", err)
	}
	if authResp.StatusCode != http.StatusFound {
		body, _ := io.ReadAll(authResp.Body)
		t.Fatalf("driveLoopback/authorize: want 302, got %d: %s", authResp.StatusCode, body)
	}
	flowCookie := ""
	for _, c := range authResp.Cookies() {
		if c.Name == "as_flow" {
			flowCookie = c.Value
		}
	}
	if flowCookie == "" {
		t.Fatal("driveLoopback: no as_flow cookie")
	}
	ghURL := authResp.Header.Get("Location")

	ghResp, err := cl.Get(ghURL)
	if err != nil {
		t.Fatalf("driveLoopback/githubfake: %v", err)
	}
	callbackURL := ghResp.Header.Get("Location")
	if callbackURL == "" {
		t.Fatalf("driveLoopback/githubfake: no Location, status=%d", ghResp.StatusCode)
	}

	cbReq, _ := http.NewRequest("GET", callbackURL, nil)
	cbReq.AddCookie(&http.Cookie{Name: "as_flow", Value: flowCookie})
	cbResp, err := cl.Do(cbReq)
	if err != nil {
		t.Fatalf("driveLoopback/callback: %v", err)
	}
	if cbResp.StatusCode != http.StatusFound {
		body, _ := io.ReadAll(cbResp.Body)
		t.Fatalf("driveLoopback/callback: want 302, got %d: %s", cbResp.StatusCode, body)
	}
	// Follow final redirect to spawnctl's /cb listener.
	finalURL := cbResp.Header.Get("Location")
	finalResp, err := http.Get(finalURL)
	if err != nil {
		t.Fatalf("driveLoopback/cb hit: %v", err)
	}
	finalResp.Body.Close()
}

// TestLoopbackLoginEndToEnd: loopback PKCE flow writes auth.json with access + refresh + key.
// Uses --no-browser so loginLoopback prints the URL; the test parses it to drive the flow.
func TestLoopbackLoginEndToEnd(t *testing.T) {
	fake := githubfake.New()
	defer fake.Close()
	fake.SetUser(10002, "looptest2")
	now := time.Unix(1770000000, 0)
	srv, _, _ := buildTestAS(t, fake, func() time.Time { return now })

	dir := t.TempDir()

	// loginLoopback writes the authorize URL to pw; test reads from pr.
	pr, pw := io.Pipe()

	loginErrCh := make(chan error, 1)
	go func() {
		err := loginLoopback(context.Background(), dir, srv.URL, true, pw)
		pw.CloseWithError(err) // propagate error through pipe
		loginErrCh <- err
	}()

	// Read lines until we find the authorize URL.
	scanner := bufio.NewScanner(pr)
	var authURL string
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, srv.URL+"/oauth/authorize") {
			authURL = line
			break
		}
	}
	if authURL == "" {
		t.Fatal("could not find authorize URL in loginLoopback output")
	}

	// Extract cbURL and session pubkey from the authorize URL.
	parsedAuth, err := url.Parse(authURL)
	if err != nil {
		t.Fatalf("parse authorize URL: %v", err)
	}
	cbURL := parsedAuth.Query().Get("redirect_uri")
	sessKeyB64 := parsedAuth.Query().Get("session_pubkey")
	csrfState := parsedAuth.Query().Get("state")
	if cbURL == "" || sessKeyB64 == "" || csrfState == "" {
		t.Fatalf("missing redirect_uri, session_pubkey, or state in authorize URL: %s", authURL)
	}

	// Drive the browser flow using the CSRF state generated by loginLoopback.
	driveLoopbackFlow(t, srv, fake, cbURL, sessKeyB64, csrfState)

	// Drain remaining output so loginLoopback can finish writing.
	go io.Copy(io.Discard, pr)

	if err := <-loginErrCh; err != nil {
		t.Fatalf("loginLoopback: %v", err)
	}

	// Verify auth.json.
	info, err := os.Stat(filepath.Join(dir, authStateFile))
	if err != nil {
		t.Fatalf("auth.json missing: %v", err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("auth.json perms: want 0600, got %o", info.Mode().Perm())
	}
	s, err := loadState(dir)
	if err != nil || s == nil {
		t.Fatalf("loadState: %v", err)
	}
	if s.AccessToken == "" {
		t.Fatal("access_token empty")
	}
	if s.RefreshToken == "" {
		t.Fatal("refresh_token empty — loopback refresh_token seam not working")
	}
	if s.SessionKeyPKCS8PEM == "" {
		t.Fatal("session_key_pkcs8_pem empty")
	}
	// Bearer header check: token source returns the stored access token.
	src := buildTokenSource(dir, "dev-token", &http.Client{})
	tok, err := src.Token(context.Background())
	if err != nil {
		t.Fatalf("Token: %v", err)
	}
	if tok != s.AccessToken {
		t.Fatalf("token source returned %q; want stored access token %q", tok, s.AccessToken)
	}
}

// TestDeviceFlow: device grant persists tokens on approval.
// Note: the poll interval from the real AS is 5s; test may take ~5s.
func TestDeviceFlow(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping device flow test in short mode (polls 5s)")
	}

	fake := githubfake.New()
	defer fake.Close()
	fake.SetUser(10003, "devtest")
	now := time.Unix(1770000000, 0)
	srv, st, _ := buildTestAS(t, fake, func() time.Time { return now })

	dir := t.TempDir()

	// Capture loginDevice's output through a pipe to extract the user_code.
	pr, pw := io.Pipe()
	loginErrCh := make(chan error, 1)
	go func() {
		err := loginDevice(context.Background(), dir, srv.URL, pw)
		pw.CloseWithError(err)
		loginErrCh <- err
	}()

	// Read lines until we find the user_code line.
	scanner := bufio.NewScanner(pr)
	var userCode string
	for scanner.Scan() {
		line := scanner.Text()
		if strings.Contains(line, "And enter code:") {
			parts := strings.Fields(line)
			if len(parts) > 0 {
				userCode = parts[len(parts)-1]
			}
			break
		}
	}
	if userCode == "" {
		t.Fatal("could not capture user_code from loginDevice output")
	}

	// Seed a browser session and approve the grant.
	seedLoginTestUser(t, st, "acct-dev", 10003, now)
	browserToken := seedLoginTestFamily(t, st, "acct-dev", now)

	verifyReq, _ := http.NewRequest("POST", srv.URL+"/device/verify",
		strings.NewReader(url.Values{"user_code": {userCode}}.Encode()))
	verifyReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	verifyReq.AddCookie(&http.Cookie{Name: "device_session", Value: browserToken, Path: "/device"})
	resp, err := http.DefaultClient.Do(verifyReq)
	if err != nil {
		t.Fatalf("device/verify: %v", err)
	}
	resp.Body.Close()

	// Drain remaining output and wait for loginDevice to finish.
	go io.Copy(io.Discard, pr)

	if err := <-loginErrCh; err != nil {
		t.Fatalf("loginDevice: %v", err)
	}

	s, err := loadState(dir)
	if err != nil || s == nil {
		t.Fatalf("loadState: %v", err)
	}
	if s.AccessToken == "" {
		t.Fatal("access_token empty after device flow")
	}
	if s.RefreshToken == "" {
		t.Fatal("refresh_token empty after device flow")
	}
	if s.SessionKeyPKCS8PEM == "" {
		t.Fatal("session key empty after device flow")
	}
}

// TestConcurrentRefreshSingleFlight: N goroutines call Token() on a near-expiry state;
// exactly one /refresh must reach the AS; all goroutines get the same fresh token.
func TestConcurrentRefreshSingleFlight(t *testing.T) {
	fake := githubfake.New()
	defer fake.Close()
	fake.SetUser(10004, "refreshtest")
	// Use nil (real time) for the AS clock — PoP signatures use time.Now() and must not skew.
	// Seeded sessions must also use time.Now() so they are not already expired at real time.
	srv, st, _ := buildTestAS(t, fake, nil)

	dir := t.TempDir()

	// Generate a session key and get a real refresh family via device grant.
	sessKey, err := generateSessionKey()
	if err != nil {
		t.Fatal(err)
	}
	pubB64, err := sessionPubkeySPKIB64(sessKey)
	if err != nil {
		t.Fatal(err)
	}
	spkiDER, _ := x509.MarshalPKIXPublicKey(&sessKey.PublicKey)
	keyPEM, err := marshalSessionKey(sessKey)
	if err != nil {
		t.Fatal(err)
	}

	// Seed user + device grant + approve it.
	seedLoginTestUser(t, st, "acct-refresh", 10004, time.Now())

	form := url.Values{"session_pubkey": {pubB64}, "client_kind": {"cli"}}
	authResp, err := http.PostForm(srv.URL+"/device/authorize", form)
	if err != nil {
		t.Fatal(err)
	}
	var authOut struct {
		DeviceCode string `json:"device_code"`
		UserCode   string `json:"user_code"`
	}
	body, _ := io.ReadAll(authResp.Body)
	authResp.Body.Close()
	if err := json.Unmarshal(body, &authOut); err != nil || authOut.DeviceCode == "" {
		t.Fatalf("device/authorize: %v: %s", err, body)
	}

	// Seed with real time so the session is not already expired when the AS (using real time) checks it.
	browserToken := seedLoginTestFamilyWithSPKI(t, st, "acct-refresh", spkiDER, time.Now())
	verifyReq, _ := http.NewRequest("POST", srv.URL+"/device/verify",
		strings.NewReader(url.Values{"user_code": {authOut.UserCode}}.Encode()))
	verifyReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	verifyReq.AddCookie(&http.Cookie{Name: "device_session", Value: browserToken, Path: "/device"})
	vr, _ := http.DefaultClient.Do(verifyReq)
	if vr != nil {
		vrBody, _ := io.ReadAll(vr.Body)
		vr.Body.Close()
		if vr.StatusCode != http.StatusOK {
			t.Fatalf("device/verify: status=%d body=%s", vr.StatusCode, vrBody)
		}
	}

	// Poll for tokens.
	var tokenOut struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	for i := 0; i < 20; i++ {
		time.Sleep(100 * time.Millisecond)
		tr, err := http.PostForm(srv.URL+"/device/token",
			url.Values{"device_code": {authOut.DeviceCode}})
		if err != nil {
			continue
		}
		b2, _ := io.ReadAll(tr.Body)
		tr.Body.Close()
		if json.Unmarshal(b2, &tokenOut) == nil && tokenOut.AccessToken != "" {
			break
		}
	}
	if tokenOut.AccessToken == "" {
		t.Fatal("could not get tokens via device flow for refresh test setup")
	}

	// Seed a near-expiry authState.
	s := &authState{
		ASURL:              srv.URL,
		AccessToken:        tokenOut.AccessToken,
		AccessExpiresAt:    time.Now().Add(5 * time.Second).Unix(), // within refreshWindow (2min)
		RefreshToken:       tokenOut.RefreshToken,
		SessionKeyPKCS8PEM: keyPEM,
	}
	if err := saveState(dir, s); err != nil {
		t.Fatal(err)
	}

	// Wrap the server's handler with a /refresh counter.
	origHandler := srv.Config.Handler
	var refreshCount int32
	srv.Config.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost && r.URL.Path == "/refresh" {
			atomic.AddInt32(&refreshCount, 1)
		}
		origHandler.ServeHTTP(w, r)
	})

	// Launch N goroutines calling Token() concurrently.
	const N = 10
	src := &cpTokenSource{dir: dir, httpClient: &http.Client{}}
	results := make([]string, N)
	errs := make([]error, N)
	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		i := i
		wg.Add(1)
		go func() {
			defer wg.Done()
			results[i], errs[i] = src.Token(context.Background())
		}()
	}
	wg.Wait()

	// Restore original handler.
	srv.Config.Handler = origHandler

	// Assert exactly one /refresh hit.
	if got := atomic.LoadInt32(&refreshCount); got != 1 {
		t.Fatalf("want exactly 1 /refresh, got %d", got)
	}

	// Assert all goroutines got the same non-empty token.
	first := results[0]
	if first == "" {
		t.Fatal("results[0] empty")
	}
	for i, tok := range results {
		if errs[i] != nil {
			t.Errorf("goroutine %d error: %v", i, errs[i])
		}
		if tok != first {
			t.Errorf("goroutine %d token %q != %q", i, tok, first)
		}
	}
}

// TestConcurrentRefreshFileLock: N independent cpTokenSource instances (separate in-process mutex,
// separate file-descriptor) targeting the same dir call Token() concurrently. The advisory flock
// in withFileLock must provide single-flight across the separate instances — exactly one /refresh
// must reach the AS; all callers must receive the same fresh token.
//
// This is distinct from TestConcurrentRefreshSingleFlight, which shares one cpTokenSource and
// therefore serialises via the in-process sync.Mutex. Here each goroutine holds its own instance,
// so only the flock path is exercised.
func TestConcurrentRefreshFileLock(t *testing.T) {
	fake := githubfake.New()
	defer fake.Close()
	fake.SetUser(10006, "flocktest")
	srv, st, _ := buildTestAS(t, fake, nil)

	dir := t.TempDir()

	sessKey, err := generateSessionKey()
	if err != nil {
		t.Fatal(err)
	}
	pubB64, err := sessionPubkeySPKIB64(sessKey)
	if err != nil {
		t.Fatal(err)
	}
	spkiDER, _ := x509.MarshalPKIXPublicKey(&sessKey.PublicKey)
	keyPEM, err := marshalSessionKey(sessKey)
	if err != nil {
		t.Fatal(err)
	}

	seedLoginTestUser(t, st, "acct-flock", 10006, time.Now())

	form := url.Values{"session_pubkey": {pubB64}, "client_kind": {"cli"}}
	authResp, err := http.PostForm(srv.URL+"/device/authorize", form)
	if err != nil {
		t.Fatal(err)
	}
	var authOut struct {
		DeviceCode string `json:"device_code"`
		UserCode   string `json:"user_code"`
	}
	body, _ := io.ReadAll(authResp.Body)
	authResp.Body.Close()
	if err := json.Unmarshal(body, &authOut); err != nil || authOut.DeviceCode == "" {
		t.Fatalf("device/authorize: %v: %s", err, body)
	}

	browserToken := seedLoginTestFamilyWithSPKI(t, st, "acct-flock", spkiDER, time.Now())
	verifyReq, _ := http.NewRequest("POST", srv.URL+"/device/verify",
		strings.NewReader(url.Values{"user_code": {authOut.UserCode}}.Encode()))
	verifyReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	verifyReq.AddCookie(&http.Cookie{Name: "device_session", Value: browserToken, Path: "/device"})
	vr, _ := http.DefaultClient.Do(verifyReq)
	if vr != nil {
		vrBody, _ := io.ReadAll(vr.Body)
		vr.Body.Close()
		if vr.StatusCode != http.StatusOK {
			t.Fatalf("device/verify: status=%d body=%s", vr.StatusCode, vrBody)
		}
	}

	var tokenOut struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	for i := 0; i < 20; i++ {
		time.Sleep(100 * time.Millisecond)
		tr, err := http.PostForm(srv.URL+"/device/token",
			url.Values{"device_code": {authOut.DeviceCode}})
		if err != nil {
			continue
		}
		b2, _ := io.ReadAll(tr.Body)
		tr.Body.Close()
		if json.Unmarshal(b2, &tokenOut) == nil && tokenOut.AccessToken != "" {
			break
		}
	}
	if tokenOut.AccessToken == "" {
		t.Fatal("could not get tokens via device flow for flock test setup")
	}

	s := &authState{
		ASURL:              srv.URL,
		AccessToken:        tokenOut.AccessToken,
		AccessExpiresAt:    time.Now().Add(5 * time.Second).Unix(),
		RefreshToken:       tokenOut.RefreshToken,
		SessionKeyPKCS8PEM: keyPEM,
	}
	if err := saveState(dir, s); err != nil {
		t.Fatal(err)
	}

	origHandler := srv.Config.Handler
	var refreshCount int32
	srv.Config.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost && r.URL.Path == "/refresh" {
			atomic.AddInt32(&refreshCount, 1)
		}
		origHandler.ServeHTTP(w, r)
	})

	// Each goroutine owns its own cpTokenSource — separate mutex, separate file descriptor.
	// Only the flock serialises them; the in-process sync.Mutex plays no role here.
	const N = 10
	results := make([]string, N)
	errs := make([]error, N)
	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		i := i
		wg.Add(1)
		go func() {
			defer wg.Done()
			src := &cpTokenSource{dir: dir, httpClient: &http.Client{}}
			results[i], errs[i] = src.Token(context.Background())
		}()
	}
	wg.Wait()

	srv.Config.Handler = origHandler

	if got := atomic.LoadInt32(&refreshCount); got != 1 {
		t.Fatalf("want exactly 1 /refresh, got %d", got)
	}

	first := results[0]
	if first == "" {
		t.Fatal("results[0] empty")
	}
	for i, tok := range results {
		if errs[i] != nil {
			t.Errorf("goroutine %d error: %v", i, errs[i])
		}
		if tok != first {
			t.Errorf("goroutine %d token %q != %q", i, tok, first)
		}
	}
}

// TestLogout: logout calls /logout, revokes the family, and removes auth.json.
func TestLogout(t *testing.T) {
	fake := githubfake.New()
	defer fake.Close()
	fake.SetUser(10005, "logouttest")
	// Use nil (real time) for the AS clock — PoP verification must match time.Now() used by signRefreshPoP.
	// Seeded sessions must also use time.Now() so they are not already expired at real time.
	srv, st, _ := buildTestAS(t, fake, nil)

	dir := t.TempDir()

	sessKey, err := generateSessionKey()
	if err != nil {
		t.Fatal(err)
	}
	keyPEM, err := marshalSessionKey(sessKey)
	if err != nil {
		t.Fatal(err)
	}
	spkiDER, _ := x509.MarshalPKIXPublicKey(&sessKey.PublicKey)

	seedLoginTestUser(t, st, "acct-logout", 10005, time.Now())
	rawRefresh := seedLoginTestFamilyWithSPKI(t, st, "acct-logout", spkiDER, time.Now())

	s := &authState{
		ASURL:              srv.URL,
		AccessToken:        "fake-access",
		AccessExpiresAt:    time.Now().Add(15 * time.Minute).Unix(),
		RefreshToken:       rawRefresh,
		SessionKeyPKCS8PEM: keyPEM,
	}
	if err := saveState(dir, s); err != nil {
		t.Fatal(err)
	}

	if err := doLogout(context.Background(), dir); err != nil {
		t.Fatalf("doLogout: %v", err)
	}

	// auth.json must be gone.
	if _, err := os.Stat(filepath.Join(dir, authStateFile)); !os.IsNotExist(err) {
		t.Fatalf("auth.json should have been removed after logout, got err=%v", err)
	}

	// POST /refresh with the revoked token → 401 token_revoked.
	tsStr, nonceB64, sigB64, err := signRefreshPoP(rawRefresh, sessKey)
	if err != nil {
		t.Fatal(err)
	}
	refreshReq, _ := http.NewRequest("POST", srv.URL+"/refresh", nil)
	refreshReq.AddCookie(&http.Cookie{Name: "refresh_token", Value: rawRefresh})
	refreshReq.Header.Set("X-PoP-Timestamp", tsStr)
	refreshReq.Header.Set("X-PoP-Nonce", nonceB64)
	refreshReq.Header.Set("X-PoP-Sig", sigB64)
	refreshResp, err := http.DefaultClient.Do(refreshReq)
	if err != nil {
		t.Fatalf("post-logout refresh: %v", err)
	}
	defer refreshResp.Body.Close()
	if refreshResp.StatusCode != http.StatusUnauthorized {
		b, _ := io.ReadAll(refreshResp.Body)
		t.Fatalf("post-logout /refresh: want 401, got %d: %s", refreshResp.StatusCode, b)
	}
	var errBody struct{ Error string `json:"error"` }
	_ = json.NewDecoder(refreshResp.Body).Decode(&errBody)
	if errBody.Error != "token_revoked" {
		t.Fatalf("post-logout /refresh: want token_revoked, got %q", errBody.Error)
	}
}

// TestDevFallbackIntact: with a static env token or explicit flag, no AS calls; bearer carries it.
func TestDevFallbackIntact(t *testing.T) {
	dir := t.TempDir()
	const devToken = "test-dev-token-xyz"

	// Env override.
	t.Setenv("SPAWNERY_TOKEN", devToken)
	src := buildTokenSource(dir, "dev-token", &http.Client{})
	tok, err := src.Token(context.Background())
	if err != nil {
		t.Fatalf("Token (env): %v", err)
	}
	if tok != devToken {
		t.Fatalf("env override: want %q, got %q", devToken, tok)
	}

	// Explicit -token flag (non-default).
	t.Setenv("SPAWNERY_TOKEN", "")
	src2 := buildTokenSource(dir, "my-explicit-token", &http.Client{})
	tok2, err := src2.Token(context.Background())
	if err != nil {
		t.Fatalf("Token (flag): %v", err)
	}
	if tok2 != "my-explicit-token" {
		t.Fatalf("flag override: want my-explicit-token, got %q", tok2)
	}

	// Default "dev-token" + no env + no state → "dev-token".
	t.Setenv("SPAWNERY_TOKEN", "")
	src3 := buildTokenSource(dir, "dev-token", &http.Client{})
	tok3, _ := src3.Token(context.Background())
	if tok3 != "dev-token" {
		t.Fatalf("dev-token fallback: want dev-token, got %q", tok3)
	}
}

// TestPoPRoundTrip: signRefreshPoP → authsvc.VerifyPoP cross-validates the frozen byte layout.
func TestPoPRoundTrip(t *testing.T) {
	sessKey, err := generateSessionKey()
	if err != nil {
		t.Fatal(err)
	}
	rawRefresh := "test-refresh-token-abc"

	tsStr, nonceB64, sigB64, err := signRefreshPoP(rawRefresh, sessKey)
	if err != nil {
		t.Fatalf("signRefreshPoP: %v", err)
	}

	var ts int64
	if _, err := fmt.Sscanf(tsStr, "%d", &ts); err != nil {
		t.Fatal(err)
	}
	nonce, _ := base64.RawURLEncoding.DecodeString(nonceB64)
	sig, _ := base64.RawURLEncoding.DecodeString(sigB64)
	spkiDER, _ := x509.MarshalPKIXPublicKey(&sessKey.PublicKey)

	tokenHash := sha256.Sum256([]byte(rawRefresh))
	proof := authsvc.PoPProof{
		RefreshTokenHash: tokenHash[:],
		Timestamp:        ts,
		Nonce:            nonce,
		Sig:              sig,
	}
	if err := authsvc.VerifyPoP(spkiDER, proof, time.Unix(ts, 0)); err != nil {
		t.Fatalf("VerifyPoP: %v", err)
	}
}

// TestPoPP1363Padding: r or s with leading zero bytes still produce a valid 64-byte sig.
func TestPoPP1363Padding(t *testing.T) {
	for i := 0; i < 50; i++ {
		sessKey, _ := generateSessionKey()
		rawRefresh := fmt.Sprintf("token-%d", i)
		tsStr, nonceB64, sigB64, err := signRefreshPoP(rawRefresh, sessKey)
		if err != nil {
			t.Fatalf("trial %d signRefreshPoP: %v", i, err)
		}
		sigBytes, _ := base64.RawURLEncoding.DecodeString(sigB64)
		if len(sigBytes) != 64 {
			t.Fatalf("trial %d: sig len %d, want 64", i, len(sigBytes))
		}
		var ts int64
		fmt.Sscanf(tsStr, "%d", &ts) //nolint:errcheck
		nonce, _ := base64.RawURLEncoding.DecodeString(nonceB64)
		spkiDER, _ := x509.MarshalPKIXPublicKey(&sessKey.PublicKey)
		tokenHash := sha256.Sum256([]byte(rawRefresh))
		proof := authsvc.PoPProof{
			RefreshTokenHash: tokenHash[:],
			Timestamp:        ts,
			Nonce:            nonce,
			Sig:              sigBytes,
		}
		if err := authsvc.VerifyPoP(spkiDER, proof, time.Unix(ts, 0)); err != nil {
			t.Fatalf("trial %d VerifyPoP: %v", i, err)
		}
	}
}

// TestAtomicRenamePerms: saveState writes 0600 and loadState round-trips.
func TestAtomicRenamePerms(t *testing.T) {
	dir := t.TempDir()
	s := &authState{
		ASURL:        "https://as.example.com",
		AccessToken:  "at",
		RefreshToken: "rt",
	}
	if err := saveState(dir, s); err != nil {
		t.Fatalf("saveState: %v", err)
	}
	info, err := os.Stat(filepath.Join(dir, authStateFile))
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Fatalf("perms: want 0600, got %o", info.Mode().Perm())
	}
	loaded, err := loadState(dir)
	if err != nil || loaded == nil {
		t.Fatalf("loadState: %v", err)
	}
	if loaded.AccessToken != "at" || loaded.RefreshToken != "rt" {
		t.Fatalf("round-trip: %+v", loaded)
	}
}

// TestStateKeyRoundTrip: ECDSA P-256 key round-trips through PKCS8 PEM.
func TestStateKeyRoundTrip(t *testing.T) {
	key, err := generateSessionKey()
	if err != nil {
		t.Fatal(err)
	}
	pemStr, err := marshalSessionKey(key)
	if err != nil {
		t.Fatal(err)
	}
	key2, err := parseSessionKey(pemStr)
	if err != nil {
		t.Fatalf("parseSessionKey: %v", err)
	}
	pemStr2, _ := marshalSessionKey(key2)
	if pemStr != pemStr2 {
		t.Fatal("key PEM did not round-trip")
	}
}

// --- test helpers ---

func seedLoginTestUser(t *testing.T, st store.Store, accountID string, sub int64, now time.Time) {
	t.Helper()
	u := store.User{
		AccountID: accountID, GithubSub: sub, Handle: "h",
		Status: store.UserActive, CreatedAt: now.Unix(),
	}
	if err := st.Users().Create(context.Background(), u); err != nil {
		t.Fatal(err)
	}
}

func seedLoginTestFamily(t *testing.T, st store.Store, accountID string, now time.Time) string {
	t.Helper()
	_, spkiDER := genLoginTestP256(t)
	return seedLoginTestFamilyWithSPKI(t, st, accountID, spkiDER, now)
}

func seedLoginTestFamilyWithSPKI(t *testing.T, st store.Store, accountID string, spkiDER []byte, now time.Time) string {
	t.Helper()
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		t.Fatal(err)
	}
	rawToken := base64.RawURLEncoding.EncodeToString(b)
	sum := sha256.Sum256([]byte(rawToken))
	tokenHash := fmt.Sprintf("%x", sum[:])

	row := store.RefreshSession{
		TokenHash:         tokenHash,
		AccountID:         accountID,
		FamilyID:          "fam-" + accountID,
		ClientKind:        store.ClientCLI,
		SessionPubkeySPKI: spkiDER,
		AccessTokenID:     "tok-" + accountID,
		CreatedAt:         now.Unix(),
		LastUsedAt:        now.Unix(),
		ExpiresAt:         now.Add(30 * 24 * time.Hour).Unix(),
		FamilyCreatedAt:   now.Unix(),
	}
	if err := st.RefreshSessions().Insert(context.Background(), row); err != nil {
		t.Fatal(err)
	}
	return rawToken
}

func genLoginTestP256(t *testing.T) (*ecdsa.PrivateKey, []byte) {
	t.Helper()
	k, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	der, err := x509.MarshalPKIXPublicKey(&k.PublicKey)
	if err != nil {
		t.Fatal(err)
	}
	return k, der
}

// Unused in the test file but referenced for completeness — keeps the import alive.
var _ = binary.BigEndian
