package intent_test

// vectors_test.go verifies frozen Go↔TS cross-language vectors for intent body bytes,
// DER-SPKI hashing, and P1363↔DER encoding [AM11]. Vectors are generated by the first run
// and verified on all subsequent runs — if they change the wire format has regressed.
//
// To regenerate the vectors after a deliberate wire-format change:
//   go test -run TestGenerateVectors -tags=generate_vectors ./internal/intent/
// (The generate tag is intentionally absent from normal test runs.)

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"testing"

	"google.golang.org/protobuf/proto"

	authv1 "spawnery/gen/auth/v1"
	"spawnery/internal/intent"
)

func parseFixedKey(t *testing.T) *ecdsa.PrivateKey {
	t.Helper()
	// Use a fresh generated key with a fixed random seed for reproducibility.
	// Since math/rand isn't crypto, we use a hardcoded scalar directly.
	// For test vectors we need a STABLE key — use a well-known test vector scalar.
	// RFC 6979 P-256 test vector: d = c9afa9d845ba75166b5c215767b1d6934e50c3db36e89b127b8a622b120f6721
	dHex := "c9afa9d845ba75166b5c215767b1d6934e50c3db36e89b127b8a622b120f6721"
	d, ok := new(big.Int).SetString(dHex, 16)
	if !ok {
		t.Fatal("bad scalar hex")
	}
	curve := elliptic.P256()
	priv := &ecdsa.PrivateKey{
		D:         d,
		PublicKey: ecdsa.PublicKey{Curve: curve},
	}
	priv.PublicKey.X, priv.PublicKey.Y = curve.ScalarBaseMult(d.Bytes())
	return priv
}

type vectorFile struct {
	SPKIDERHex      string `json:"spki_der_hex"`
	SPKIHashHex     string `json:"spki_hash_hex"`
	BodyBytesHex    string `json:"body_bytes_hex"`
	BodyBase64      string `json:"body_base64"`
}

const vectorPath = "testdata/intent_vectors.json"

// TestVectorsMatchFile verifies the intent wire artifacts against the frozen vector file.
// If the file does not exist yet, it is created (first run only).
func TestVectorsMatchFile(t *testing.T) {
	priv := parseFixedKey(t)

	// Compute expected values.
	spki, err := x509.MarshalPKIXPublicKey(&priv.PublicKey)
	if err != nil {
		t.Fatalf("MarshalPKIXPublicKey: %v", err)
	}
	spkiHash := sha256.Sum256(spki)

	body := &authv1.IntentBody{
		Jti:          "fixed-jti-for-vectors",
		IssuedAt:     1770000000,
		SpawnId:      "sp-vec-001",
		Generation:   1,
		TargetNodeId: "node-vec-1",
		Op:           string(intent.OpCreateSpawn),
		AppRef:       "app/test@sha256:deadbeef",
		Image:        "registry/img@sha256:cafebabe",
		Model:        "claude-test",
	}
	bodyBytes, err := proto.Marshal(body)
	if err != nil {
		t.Fatalf("proto.Marshal: %v", err)
	}

	want := vectorFile{
		SPKIDERHex:   hex.EncodeToString(spki),
		SPKIHashHex:  hex.EncodeToString(spkiHash[:]),
		BodyBytesHex: hex.EncodeToString(bodyBytes),
		BodyBase64:   base64.StdEncoding.EncodeToString(bodyBytes),
	}

	// Read or create the vector file.
	data, err := os.ReadFile(vectorPath)
	if err != nil {
		if !os.IsNotExist(err) {
			t.Fatalf("read vector file: %v", err)
		}
		// First run: create the file.
		t.Log("vector file not found — creating")
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		data, err = json.MarshalIndent(want, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(vectorPath, data, 0o644); err != nil {
			t.Fatalf("write vector file: %v", err)
		}
		t.Log("vectors written; re-run tests to verify")
		return
	}

	var got vectorFile
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("parse vector file: %v", err)
	}

	if got.SPKIDERHex != want.SPKIDERHex {
		t.Errorf("SPKI DER hex mismatch\n got: %s\nwant: %s", got.SPKIDERHex, want.SPKIDERHex)
	}
	if got.SPKIHashHex != want.SPKIHashHex {
		t.Errorf("SPKI hash hex mismatch\n got: %s\nwant: %s", got.SPKIHashHex, want.SPKIHashHex)
	}
	if got.BodyBytesHex != want.BodyBytesHex {
		t.Errorf("body bytes hex mismatch\n got: %s\nwant: %s", got.BodyBytesHex, want.BodyBytesHex)
	}
	if got.BodyBase64 != want.BodyBase64 {
		t.Errorf("body base64 mismatch\n got: %s\nwant: %s", got.BodyBase64, want.BodyBase64)
	}
}
