#!/usr/bin/env bash
# up.sh — boot ONE e2e VM instance from the golden image and wait for SSH.
# Concurrency-safe: a unique domain/overlay/hostname per E2E_RUNID.
# Prints the instance's ACC_* base values to STATE/acc.env. Does NOT roll fresh code
# or wait for the app to be ready — roll.sh does that (so binaries land before readiness).
#
# Usage: E2E_RUNID=... GOLDEN_IMAGE=/path/golden.qcow2 ./up.sh [--profile fake|github]
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

PROFILE=fake
while [ $# -gt 0 ]; do case "$1" in
  --profile) PROFILE="$2"; shift 2;;
  *) die "unknown arg: $1";;
esac; done

[ -n "$GOLDEN_IMAGE" ] || die "GOLDEN_IMAGE unset (build it with build-base.sh)"
[ -f "$GOLDEN_IMAGE" ] || die "GOLDEN_IMAGE not found: $GOLDEN_IMAGE"
: "${E2E_RUNID:=$(gen_runid)}"; export E2E_RUNID
DOM="$(vm_domain)"; HOST="$(vm_hostname)"; RD="$(run_dir)"; OVL="$(overlay_path)"
mkdir -p "$RD/artifacts"
log "runid=$E2E_RUNID domain=$DOM hostname=$HOST profile=$PROFILE"

# ---- per-run overlay on the golden image (golden stays read-only) ----
qemu-img create -q -f qcow2 -F qcow2 -b "$(readlink -f "$GOLDEN_IMAGE")" "$OVL" >/dev/null
log "overlay: $OVL"

# ---- cloud-init seed: per-run hostname, ssh pubkey, and the chosen auth profile ----
# (The golden image's cloud-init consumes this; the profile is written to /etc/spawnery-e2e/profile
#  which the systemd units read to pick fake vs github auth wiring.)
SEED_DIR="$RD/seed"; mkdir -p "$SEED_DIR"
cat >"$SEED_DIR/meta-data" <<EOF
instance-id: $DOM
local-hostname: $HOST
EOF
PUBKEY="$(cat "${E2E_SSH_KEY}.pub" 2>/dev/null || die "ssh pubkey ${E2E_SSH_KEY}.pub missing")"
cat >"$SEED_DIR/user-data" <<EOF
#cloud-config
hostname: $HOST
fqdn: $HOST
users:
  - name: $E2E_SSH_USER
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: [ "$PUBKEY" ]
write_files:
  - path: /etc/spawnery-e2e/profile
    content: "$PROFILE\n"
  - path: /etc/spawnery-e2e/web_origin
    content: "https://$HOST\n"
runcmd:
  - [ systemctl, restart, chronyd ]     # correct clock on cold boot (belt-and-suspenders)
EOF
SEED_ISO="$RD/seed.iso"
genisoimage -quiet -output "$SEED_ISO" -volid cidata -joliet -rock \
  "$SEED_DIR/user-data" "$SEED_DIR/meta-data" 2>/dev/null \
  || cloud-localds "$SEED_ISO" "$SEED_DIR/user-data" "$SEED_DIR/meta-data"

# ---- render + define + start the transient domain ----
CONSOLE_LOG="$RD/artifacts/console.log"
sed -e "s#@@DOMAIN@@#$DOM#g" -e "s#@@MEM_MB@@#$E2E_VM_MEM_MB#g" -e "s#@@VCPUS@@#$E2E_VM_VCPUS#g" \
    -e "s#@@OVERLAY@@#$OVL#g" -e "s#@@SEED_ISO@@#$SEED_ISO#g" -e "s#@@NET@@#$E2E_NET#g" \
    -e "s#@@CONSOLE_LOG@@#$CONSOLE_LOG#g" \
    "$E2E_DIR/templates/domain.xml.tmpl" > "$RD/domain.xml"
virsh_ create "$RD/domain.xml" >/dev/null || die "virsh create failed (is '$E2E_NET' defined + active?)"
log "domain started; waiting for DHCP lease…"

IP="$(vm_ip "$DOM")" || { warn "no lease; see $CONSOLE_LOG"; die "VM did not get an IP"; }
log "VM IP: $IP"
host_resolve_add "$HOST" "$IP"

wait_tcp "$IP" 22 180 || die "SSH never came up on $IP; see $CONSOLE_LOG"
log "SSH up on $IP"

cat >"$RD/acc.env" <<EOF
# generated by up.sh for runid=$E2E_RUNID
export E2E_RUNID='$E2E_RUNID'
export E2E_VM_IP='$IP'
export E2E_VM_HOST='$HOST'
export ACC_WEB_ORIGIN='https://$HOST'
export ACC_CP_ENDPOINT='https://$HOST'
export ACC_AS_ORIGIN='https://$HOST'
export ACC_NODE_ADDR='http://$IP:9092'
export ACC_NODE_TERMINAL_ADDR='http://$IP:9092'
export ACC_NONPROD_HOSTS='$HOST,.$E2E_DOMAIN_SUFFIX'
export ACC_ENV='vm-$PROFILE'
EOF
log "wrote $RD/acc.env  (ACC_WEB_ORIGIN=https://$HOST)"
