store:
    dsn: ENC[AES256_GCM,data:CtnYSUyp7NCQCZvYdBEpFKlpoDKqTac9A+H6RahicPSHYKRg68CruHjxvd5LxPw0WPtDtngyFtUvqt6hWc0KzeQAbCVH,iv:n1S71ed9nDDaKw3E8g+x0uFrDp93hConE6R3BWq8f5s=,tag:LFELT6HYkANOw0xV45foSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrME1mT3RUSjYxRzVZMjdj
            dmZhRTJuOHBVM2UrWlN3V2hjeGprb1pwMldnCnlGWmZkVE9HM2hwUmt0MUN6d0xu
            VksvZFo1a1VHeHp5TWx6dSt3Z3JFbWsKLS0tIERyalo3aWZWaERWQlFkYk5LY1RB
            U0ZRR1k2ekl2V2ViMnUxaTVES3FNaDQKetHQ+VlbShlMVWY88ARQD37zztj9+OHO
            K/DfhP0rsLYmsXPTvk+zFRofgcivUTYrxpuP1+Cc6YWnKiEzW61Kjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kq88qewgw96f5kamgljvtjt7tat83gh8ztchmpvvddz5j79assvsl3f8nu
    lastmodified: "2026-06-21T04:43:41Z"
    mac: ENC[AES256_GCM,data:RBenuOmd7Qu4D2Uzi9X4bwiVWb8tqW96iIrkK8Mn5DmM+cdE1PgqVtEgQKRflBaLmSs//VGekR2/GarUD9FF6PHZx3PRdCc+eKE3qLY+kG+eaQeC/ggAKhRhp3pL8Jd9MUq3nCg0BbH2/NsFga7YrhjSjKDDTpX7HMBH/nby20E=,iv:Ad2p7neHo5GR6bxjbC69lDn5RMskCENgFNQne4p2Yqo=,tag:YQl2HHp0T2pQtjKG7PSI+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
