/**
 * RFC 9180 §A.1 test-vector validation for the HPKE primitives.
 *
 * Suite: DHKEM(X25519, HKDF-SHA256) + HKDF-SHA256 + AES-256-GCM (our suite).
 * The KEM values (ikmR/skRm/pkRm/enc) are taken directly from RFC 9180 §A.1
 * (mode=0/base, kem_id=0x0020, kdf_id=0x0001, aead_id=0x0001 — same KEM/KDF
 * as our suite; the AEAD differs but KEM and key-schedule context do not
 * affect the shared secret).
 *
 * The sealed ciphertext (ct) was generated by Go's internal/secrets/seal using
 * DHKEM(X25519)+HKDF-SHA256+AES-256-GCM, deterministically keyed from the A.1
 * ikmR/ikmE values, so the test validates end-to-end Go↔TS interoperability.
 *
 * Test vectors from:
 *   - RFC 9180 Appendix A (ikmR, skRm, pkRm, enc/pkEm)
 *   - Go/CIRCL circl/hpke (shared_secret, sealed ct)
 */

import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  dhkemDerivePrivateScalar,
  hpkeOpen,
  hpkeSeal,
  sealEnvelope,
  reSealEnvelope,
  openEnvelope,
  type RecipientSeal,
  type Envelope,
} from "./hpke";
import { deriveDeviceKeysFromMnemonic, exportDeviceRef } from "./device";

const TESTDATA_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../internal/secrets/seal/testdata/owner-seal",
);

// ── RFC 9180 §A.1 KEM values ─────────────────────────────────────────────────

// ikmR: input key material for recipient DeriveKeyPair (32 bytes, hex)
const A1_IKMR = "6db9df30aa07dd42ee5e8181afdb977e538f5e1fec8a06223f33f7013e525037";
// skRm: expected recipient private scalar after DeriveKeyPair (32 bytes, hex)
const A1_SKR  = "4612c550263fc8ad58375df3f557aac531d26850903e55a9f23f21d8534e8ac8";
// pkRm: expected recipient public key (32 bytes, hex)
const A1_PKR  = "3948cfe0ad1ddb695d780e59077195da6c56506b027329794ab02bca80815c4d";
// enc (= pkEm): sender's ephemeral public key — the "37fda3..." A.1 value (32 bytes, hex)
const A1_ENC  = "37fda3567bdbd628e88668c3c8d7e97d1d1253b6d4ea6d44c150f741f1bf4431";

// ── Go-generated sealed ciphertext (AES-256-GCM variant) ─────────────────────
//
// Generated by Go internal/secrets/seal with:
//   suite = DHKEM(X25519, HKDF-SHA256) + HKDF-SHA256 + AES-256-GCM
//   recipient ikmR = A1_IKMR above
//   ephemeral ikmE = 7268600d403fce431561aef583ee1613527cff655c1343f29812e66706df3234 (A.1 ikmE)
//   info     = "Ode on a Grecian Urn"
//   aad      = "Count-0"
//   plaintext = "Beauty is truth, truth beauty"
//
// The enc value (A1_ENC) matches A.1 because the same ephemeral ikmE was used.
const GO_CT   = "CQt9wiVBn32p6LRgvs+7lqJseWTXm4AQ05f6g4Uwoyo5exT1d22xn/XldzTg";
const GO_INFO = "Ode on a Grecian Urn";
const GO_AAD  = "Count-0";
const GO_PT   = "Beauty is truth, truth beauty";

// ── Helpers ───────────────────────────────────────────────────────────────────

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function toHex(b: Uint8Array): string {
  return Array.from(b).map((x) => x.toString(16).padStart(2, "0")).join("");
}

// Import a raw 32-byte scalar as an X25519 private key (PKCS#8 wrapper).
// OID 1.3.101.110 (id-X25519), RFC 8410.
async function importX25519Scalar(scalar: Uint8Array, extractable: boolean): Promise<CryptoKey> {
  const prefix = new Uint8Array([
    0x30, 0x2e, 0x02, 0x01, 0x00,
    0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x6e,
    0x04, 0x22, 0x04, 0x20,
  ]);
  const pkcs8 = new Uint8Array(prefix.length + 32);
  pkcs8.set(prefix);
  pkcs8.set(scalar, prefix.length);
  return crypto.subtle.importKey("pkcs8", pkcs8, { name: "X25519" }, extractable, ["deriveBits"]);
}

// Derive the X25519 public key from an extractable private key (JWK round-trip).
async function x25519PublicBytes(priv: CryptoKey): Promise<Uint8Array> {
  const jwk = await crypto.subtle.exportKey("jwk", priv);
  if (!jwk.x) throw new Error("no x in JWK");
  const b64 = jwk.x.replace(/-/g, "+").replace(/_/g, "/");
  const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
  const bin = atob(padded);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("RFC 9180 §A.1 — DHKEM(X25519, HKDF-SHA256) DeriveKeyPair", () => {
  it("dhkemDerivePrivateScalar(ikmR) matches RFC 9180 §A.1 skRm", async () => {
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    expect(toHex(scalar)).toBe(A1_SKR);
  });

  it("X25519 public key derived from A.1 skRm matches pkRm", async () => {
    const skRm = fromHex(A1_SKR);
    const priv = await importX25519Scalar(skRm, true);
    const pubBytes = await x25519PublicBytes(priv);
    expect(toHex(pubBytes)).toBe(A1_PKR);
  });

  it("DeriveKeyPair(ikmR) public key matches pkRm end-to-end", async () => {
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const priv = await importX25519Scalar(scalar, true);
    const pubBytes = await x25519PublicBytes(priv);
    expect(toHex(pubBytes)).toBe(A1_PKR);
  });
});

describe("RFC 9180 §A.1 — hpkeOpen Go↔TS interop (AES-256-GCM variant)", () => {
  it("hpkeOpen decrypts Go-sealed ciphertext using DeriveKeyPair recipient key", async () => {
    // Derive recipient keys from ikmR (same DeriveKeyPair as Go uses)
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const recipPriv = await importX25519Scalar(scalar, false);
    const recipPubBytes = await x25519PublicBytes(await importX25519Scalar(scalar, true));

    // Verify derived pubkey matches A.1 pkRm
    expect(toHex(recipPubBytes)).toBe(A1_PKR);

    // Build the RecipientSeal using the A.1 enc (37fda3...) and Go-generated ct
    const rs: RecipientSeal = {
      recipient: btoa(String.fromCharCode(...fromHex(A1_PKR))),
      enc: btoa(String.fromCharCode(...fromHex(A1_ENC))),
      ct: GO_CT,
    };

    const aad = new TextEncoder().encode(GO_AAD);
    const plaintext = await hpkeOpen(rs, recipPriv, recipPubBytes, aad, GO_INFO);

    expect(new TextDecoder().decode(plaintext)).toBe(GO_PT);
  });
});

// ── Sender-side tests — hpkeSeal + round-trip ─────────────────────────────────

describe("hpkeSeal — sender-side HPKE seal round-trip", () => {
  it("hpkeSeal+hpkeOpen round-trip with known keys", async () => {
    // Use the A.1 derived keys as a fixed recipient (private key non-extractable)
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const recipPriv = await importX25519Scalar(scalar, false);
    const recipPubExtractable = await importX25519Scalar(scalar, true);
    const recipPubBytes = await x25519PublicBytes(recipPubExtractable);

    const dek = new Uint8Array(32).fill(0xab); // fixed test DEK
    const aad = new TextEncoder().encode("test-aad");
    const info = "spawnery/secrets/seal/at-rest/v1";

    const rs = await hpkeSeal(dek, recipPubBytes, aad, info);

    // RecipientSeal fields must be base64 strings
    expect(typeof rs.enc).toBe("string");
    expect(typeof rs.ct).toBe("string");
    expect(typeof rs.recipient).toBe("string");

    // The enc field must decode to 32 bytes (ephemeral X25519 pubkey)
    const encBytes = fromHex(
      Array.from(atob(rs.enc)).map((c) => c.charCodeAt(0).toString(16).padStart(2, "0")).join(""),
    );
    expect(encBytes.length).toBe(32);

    // hpkeOpen must recover the original DEK
    const recovered = await hpkeOpen(rs, recipPriv, recipPubBytes, aad, info);
    expect(toHex(recovered)).toBe(toHex(dek));
  });

  it("hpkeSeal produces distinct ciphertexts on each call (fresh ephemeral key)", async () => {
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const recipPubExtractable = await importX25519Scalar(scalar, true);
    const recipPubBytes = await x25519PublicBytes(recipPubExtractable);
    const dek = new Uint8Array(32).fill(0xcd);
    const aad = new TextEncoder().encode("aad");

    const rs1 = await hpkeSeal(dek, recipPubBytes, aad);
    const rs2 = await hpkeSeal(dek, recipPubBytes, aad);

    // Different ephemeral keys → different enc and ct on each call
    expect(rs1.enc).not.toBe(rs2.enc);
    expect(rs1.ct).not.toBe(rs2.ct);
  });
});

describe("sealEnvelope + openEnvelope — full round-trip", () => {
  it("TS seal → TS open recovers plaintext", async () => {
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const recipPriv = await importX25519Scalar(scalar, false);
    const recipPubExtractable = await importX25519Scalar(scalar, true);
    const recipPubBytes = await x25519PublicBytes(recipPubExtractable);

    const payload = new TextEncoder().encode("my-api-key-value");
    const atRest = { account_id: "acct-1", secret_id: "sec-1", version: 1 };

    const env = await sealEnvelope(payload, [recipPubBytes], atRest);

    // Envelope structure
    expect(env.at_rest).toEqual(atRest);
    expect(env.recipients).toHaveLength(1);
    expect(typeof env.nonce).toBe("string");
    expect(typeof env.ct).toBe("string");

    // Open recovers the original plaintext
    const recovered = await openEnvelope(env, recipPriv, recipPubBytes);
    expect(new TextDecoder().decode(recovered)).toBe("my-api-key-value");
  });

  it("sealEnvelope: fresh DEK on every call [roast M2]", async () => {
    const scalar = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const recipPubExtractable = await importX25519Scalar(scalar, true);
    const recipPubBytes = await x25519PublicBytes(recipPubExtractable);
    const payload = new TextEncoder().encode("same-payload");
    const atRest = { account_id: "a", secret_id: "s", version: 1 };

    const env1 = await sealEnvelope(payload, [recipPubBytes], atRest);
    const env2 = await sealEnvelope(payload, [recipPubBytes], atRest);

    // Distinct DEK seals → distinct payload ciphertexts and distinct nonces
    expect(env1.ct).not.toBe(env2.ct);
    expect(env1.recipients[0].ct).not.toBe(env2.recipients[0].ct);
  });

  it("reSealEnvelope opens + re-seals to new member set with bumped version", async () => {
    const scalar1 = await dhkemDerivePrivateScalar(fromHex(A1_IKMR));
    const priv1 = await importX25519Scalar(scalar1, false);
    const pub1Extractable = await importX25519Scalar(scalar1, true);
    const pub1 = await x25519PublicBytes(pub1Extractable);

    // Second recipient with different ikmR
    const ikmR2 = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
    const scalar2 = await dhkemDerivePrivateScalar(fromHex(ikmR2));
    const priv2 = await importX25519Scalar(scalar2, false);
    const pub2Extractable = await importX25519Scalar(scalar2, true);
    const pub2 = await x25519PublicBytes(pub2Extractable);

    const payload = new TextEncoder().encode("secret-value");
    const atRest = { account_id: "acct-1", secret_id: "sec-1", version: 5 };

    // Seal to recipient 1 only
    const env = await sealEnvelope(payload, [pub1], atRest);

    // Re-seal to both recipients; version must be bumped
    const resealed = await reSealEnvelope(env, priv1, pub1, [pub1, pub2]);

    expect(resealed.at_rest.version).toBe(6);
    expect(resealed.recipients).toHaveLength(2);
    // Both recipients can open it
    const r1 = await openEnvelope(resealed, priv1, pub1);
    const r2 = await openEnvelope(resealed, priv2, pub2);
    expect(new TextDecoder().decode(r1)).toBe("secret-value");
    expect(new TextDecoder().decode(r2)).toBe("secret-value");
  });
});

// ── Cross-language: Go-sealed envelope opened by TS ──────────────────────────
// The seal_envelope.json vector was generated by Go's vectors_test.go using
// the vectorMnemonicDevice1 mnemonic as the recipient. This validates that
// TS sealEnvelope output is compatible with Go's seal.Open format (the Go→TS
// direction is tested here; the TS→Go direction is validated by the Go-side
// roundtrip in seal_test.go and the shared encodeFields/HKDF wiring).

interface SealEnvelopeVector {
  recipient_mnemonic: string;
  plaintext_b64: string;
  account_id: string;
  secret_id: string;
  version: number;
  envelope: Envelope;
}

describe("Go-sealed envelope — cross-language open [WM9]", () => {
  const vectorPath = path.join(TESTDATA_DIR, "seal_envelope.json");
  const raw = fs.readFileSync(vectorPath, "utf8");
  const v: SealEnvelopeVector = JSON.parse(raw);

  it("TS openEnvelope recovers Go-sealed plaintext", async () => {
    const keys = await deriveDeviceKeysFromMnemonic(v.recipient_mnemonic, "");
    const ref = await exportDeviceRef(keys);

    const plaintext = await openEnvelope(v.envelope, keys.x25519Private, ref.x25519Pub);

    const expectedBytes = Uint8Array.from(atob(v.plaintext_b64), (c) => c.charCodeAt(0));
    expect(toHex(plaintext)).toBe(toHex(expectedBytes));
  });
});
